import { useState } from 'react';
import { Copy, Check, Plug, Code2, ExternalLink, Terminal, ArrowUpRight, Sparkles } from 'lucide-react';
import useAppStore from '../hooks/useAppStore';

const clients = [
    { name: 'Claude Desktop', path: '~/Library/Application Support/Claude/claude_desktop_config.json', docs: 'https://modelcontextprotocol.io/quickstart/user' },
    { name: 'Cursor', path: '~/.cursor/mcp.json', docs: 'https://docs.cursor.com/context/mcp' },
    { name: 'Kiro', path: '~/.kiro/settings/mcp.json', docs: 'https://kiro.dev/docs/mcp/' },
    { name: 'VS Code', path: 'MCP: Open User Configuration', docs: 'https://code.visualstudio.com/docs/copilot/chat/mcp-servers' }
];

const McpIntegration = () => {
    const { currentPlan } = useAppStore();
    const [copied, setCopied] = useState('');
    const repoUrl = `${window.location.origin}/mcp/repo`;
    const contextUrl = `${window.location.origin}/mcp/context`;
    const servers = [
        { key: 'repo', name: 'Repository analyzer', detail: 'Explore repository structure and read project files.', endpoint: repoUrl, tools: ['analyze_project', 'read_file', 'read_files'], color: 'indigo' },
        { key: 'context', name: 'Learning context', detail: 'Share the current plan, milestone, and progress with your AI client.', endpoint: `${contextUrl}/${currentPlan?.id || '{planId}'}`, tools: ['get_learning_plan', 'get_current_milestone', 'get_socratic_guidance', 'get_milestone_details', 'get_progress'], color: 'violet' }
    ];
    const config = { mcpServers: { 'repo-analyzer': { command: 'npx', args: ['-y', 'supergateway', '--streamableHttp', servers[0].endpoint] }, buildspace: { command: 'npx', args: ['-y', 'supergateway', '--streamableHttp', servers[1].endpoint] } } };
    const copy = async (text: string, key: string) => { try { await navigator.clipboard.writeText(text); setCopied(key); window.setTimeout(() => setCopied(''), 1800); } catch { setCopied(''); } };

    return <div className="mx-auto max-w-5xl space-y-8 pb-10">
        <header><p className="eyebrow">Bring your context with you</p><div className="mt-1 flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-700"><Plug className="h-5 w-5" /></span><h1 className="page-heading">Connect your tools</h1></div><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Use Buildspace’s MCP servers in your favorite AI coding client. Your learning roadmap and repository context stay close at hand.</p></header>
        <section className="grid gap-4 sm:grid-cols-3">{[{ number: '01', title: 'Choose a client', text: 'Use any MCP-compatible coding assistant.' }, { number: '02', title: 'Add the config', text: 'Copy the server setup below into its config.' }, { number: '03', title: 'Start a session', text: 'Restart your client and ask about your project.' }].map((step) => <div key={step.number} className="surface p-5"><span className="text-xs font-extrabold tracking-widest text-indigo-600">{step.number}</span><h2 className="mt-3 text-sm font-extrabold text-slate-900">{step.title}</h2><p className="mt-1.5 text-xs leading-5 text-slate-500">{step.text}</p></div>)}</section>
        <section><div className="mb-4"><p className="eyebrow">Available connections</p><h2 className="mt-1 text-xl font-extrabold text-slate-900">Buildspace MCP servers</h2></div><div className="grid gap-4 lg:grid-cols-2">{servers.map((server) => <article key={server.key} className="surface overflow-hidden"><div className="flex items-start gap-3 border-b border-slate-100 px-5 py-4"><span className={`flex h-9 w-9 shrink-0 items-center justify-center rounded-xl ${server.color === 'indigo' ? 'bg-indigo-50 text-indigo-700' : 'bg-violet-50 text-violet-700'}`}><Code2 className="h-4 w-4" /></span><div><h3 className="text-sm font-extrabold text-slate-900">{server.name}</h3><p className="mt-1 text-xs leading-5 text-slate-500">{server.detail}</p></div></div><div className="p-5">{server.key === 'context' && !currentPlan && <p className="mb-3 rounded-xl border border-amber-200 bg-amber-50 px-3 py-2 text-xs leading-5 text-amber-800">Select a learning plan first. Replace <code className="rounded bg-amber-100 px-1">{'{planId}'}</code> with your plan ID.</p>}<div className="mb-2 flex items-center justify-between"><span className="eyebrow">Endpoint</span><button onClick={() => copy(server.endpoint, `${server.key}-url`)} className="inline-flex items-center gap-1.5 text-xs font-bold text-indigo-700 hover:text-indigo-900">{copied === `${server.key}-url` ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}{copied === `${server.key}-url` ? 'Copied' : 'Copy URL'}</button></div><code className="block break-all rounded-xl bg-slate-950 px-3.5 py-3 font-mono text-xs leading-5 text-indigo-100">{server.endpoint}</code><div className="mt-4"><p className="eyebrow mb-2">Tools included</p><div className="flex flex-wrap gap-1.5">{server.tools.map((tool) => <span key={tool} className="rounded-md bg-slate-100 px-2 py-1 font-mono text-[10px] font-medium text-slate-600">{tool}</span>)}</div></div></div></article>)}</div></section>
        <section className="surface overflow-hidden"><div className="flex flex-col justify-between gap-3 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:px-6"><div><p className="eyebrow">One config for both servers</p><h2 className="mt-1 text-base font-extrabold text-slate-900">Add Buildspace to your client</h2></div><button onClick={() => copy(JSON.stringify(config, null, 2), 'all-config')} className="button-secondary self-start py-2 text-xs sm:self-auto">{copied === 'all-config' ? <Check className="h-3.5 w-3.5" /> : <Copy className="h-3.5 w-3.5" />}{copied === 'all-config' ? 'Copied config' : 'Copy config'}</button></div><div className="grid lg:grid-cols-[1fr_270px]"><pre className="overflow-x-auto bg-slate-950 p-5 text-[11px] leading-5 text-slate-200 sm:p-6"><code>{JSON.stringify(config, null, 2)}</code></pre><div className="border-t border-slate-100 p-5 lg:border-l lg:border-t-0 sm:p-6"><div className="flex items-center gap-2 text-slate-800"><Terminal className="h-4 w-4 text-indigo-600" /><h3 className="text-sm font-extrabold">Before you start</h3></div><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-500"><li>Node.js and npx should be installed.</li><li>Restart your AI client after updating its config.</li><li>Keep Buildspace open while using your learning context.</li></ul></div></div></section>
        <section><div className="mb-4"><p className="eyebrow">Client guides</p><h2 className="mt-1 text-xl font-extrabold text-slate-900">Where to add the config</h2></div><div className="grid gap-3 sm:grid-cols-2">{clients.map((client) => <a key={client.name} href={client.docs} target="_blank" rel="noreferrer" className="surface group flex items-center justify-between gap-4 p-4 transition hover:-translate-y-0.5 hover:border-indigo-200 hover:shadow-md"><div className="min-w-0"><h3 className="text-sm font-bold text-slate-800">{client.name}</h3><code className="mt-1 block truncate text-[11px] text-slate-400">{client.path}</code></div><ArrowUpRight className="h-4 w-4 shrink-0 text-slate-300 transition group-hover:text-indigo-600" /></a>)}</div></section>
        <a href="https://modelcontextprotocol.io/introduction" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs font-semibold text-slate-500 transition hover:text-indigo-700"><Sparkles className="h-3.5 w-3.5" /> Learn about Model Context Protocol <ExternalLink className="h-3 w-3" /></a>
    </div>;
};

export default McpIntegration;
